name: is-interactive-tty
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: original
        run: 'echo "original: [${-}]"'
      - name: x-cmd
        uses: x-cmd/action@main
        with:
          code: 'echo "x-cmd: [${-}]"'