name: is-interactive-tty
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: original
        run: |
          if [ "${-#*i}" != "$-" ]; then
            echo "Original Interactive"
          else
            echo "Original Not Interactive"
          fi
      - name: X-CMD
        uses: x-cmd/action@main
        with:
          code: |
            if [ "${-#*i}" != "$-" ]; then
              echo "X-CMD Interactive"
            else
              echo "X-CMD Not Interactive"
            fi