name: test dev file
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: main
        run: |
          [ -r /dev/tty ] && echo rrr
          [ -p /dev/tty ] && echo ppp
          [ -e /dev/tty ] && echo eee

          if sync /dev/tty 2>/dev/null; then
            echo yyy
            command stty size < /dev/tty
          else
            echo nnn
          fi
