name: test dev file
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: main
        # uses: x-cmd/action@main
            # sync /dev/tty && echo sync
            # # -e -r
            # if [ -w /dev/tty ]; then
            #   echo yyy
            #   command stty size < /dev/tty
            # else
            #   echo nnn
            # fi
        run: |
          if sync /dev/tty 2>/dev/null; then
            echo yyy
            command stty size < /dev/tty
          else
            echo nnn
          fi
